### ISSUE TITLE
fm_sewers_dev todo

### ISSUE THREAD

**Issue by Donkie** [GMDevinity/FloodIssues#394]
- [ ] Add invisible walls around play area and increase map boundary z
- [ ] Fix invisible wall / buggy water thing around the big gates
- [ ] Remove pillar / make it smaller / replace with lattice thing
- [ ] Make water less poop, transparent
