### ISSUE TITLE
New weapons todo

### ISSUE THREAD

**Issue by Donkie** [GMDevinity/FloodIssues#453]
- [x] Call GiveBow 
- [x] Call RefundNoloadItems
- [x] Call RefundWeapons
- [x] Replace `rounds_weapons_new` with `rounds_weapons` in code
- [x] Replace `playerweapons_new` with `playerweapons` in code
- [x] Call RenameWepTables

- [ ] TFA weapon shots/hits are not logged

**Comment by CounterCraftz** [comment]
change scope of awp and g2 contender to the one used on fmbase (old base)
