### ISSUE TITLE
Flood weapons todo

### ISSUE THREAD

**Issue by CounterCraftz** [GMDevinity/FloodIssues#482]
- [ ] https://cdn.discordapp.com/attachments/392542965425504256/453944038534676494/Screenshot_20180606-113121.png

- [ ] https://cdn.discordapp.com/attachments/355850966467215361/452440627431604224/Screenshot_20180602-075555.png

- [ ] https://cdn.discordapp.com/attachments/355850966467215361/452440635341799424/Screenshot_20180602-075606.png
